config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  resources :contact_messages, only: [:new, :create]
  get '/contact', to: 'contact_messages#new', as: 'new_contact'
  post '/contact', to: 'contact_messages#create', as: 'create_contact'
  get '/about', to: 'pages#about', as: 'about'
  get '/blog', to: 'pages#blog', as: 'blog'
  get 'article', to: 'pages#article', as: 'article'
  get 'services/projets_sur_mesure', to: 'services#projets_sur_mesure', as: 'services_projets_sur_mesure'
  get 'services/modernisation_projets', to: 'services#modernisation_projets', as: 'services_modernisation_projets'
  get 'services/maintenance_active', to: 'services#maintenance_active', as: 'services_maintenance_active'
  get 'services/contenu_seo_strategique', to: 'services#contenu_seo_strategique', as: 'services_contenu_seo_strategique'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact_message.rb
class ContactMessage < ApplicationRecord
  validates :name, presence: true
  validates :first_name, presence: true
  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "Adresse e-mail invalide" }
  validates :phone, presence: true, format: { with: /\A\d{10}\z/, message: "Format de téléphone invalide" }
  validates :budget, presence: true
  validates :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_messages_controller.rb
class ContactMessagesController < ApplicationController
  def new
    @contact_message = ContactMessage.new
  end

  def create
    @contact_message = ContactMessage.new(contact_message_params)

    if @contact_message.save
      flash[:success] = "Le formulaire a été envoyé avec succès."
      redirect_to request.referrer
    else
      flash[:error] = "Erreur lors de l'envoi du formulaire. Veuillez réessayer."
      render 'new'
    end
  end

  private

  def contact_message_params
    params.require(:contact_message).permit(:name, :first_name, :email, :phone, :budget, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def projets_sur_mesure
  end

  def modernisation_projets
  end

  def maintenance_active
  end

  def contenu_seo_strategique
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contact_messages/new.html.erb
<div class="background-contact">
  <div class="container">
    <div class="row">
      <div class="col-md-10 offset-md-1">
        <h2 class="contact-title">Contactez-nous</h2>
        <h3 class="contact-question">Une question ?<br>Un projet ?</h3>
        <h3 class="contact-texte">Nous réalisons à vos côtés <br>une application web ou mobile <br>au service de la croissance de votre business</h3>
        <%= simple_form_for(@contact_message, url: contact_messages_path, html: { class: 'needs-validation' }) do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

          <div class="row">
            <div class="col-md-6">
              <div class="form-group mb-5 d-flex flex-column align-items-start">
                <p><%= f.label :name, 'Nom' %></p>
                <%= f.text_field :name, class: 'form-control w-100', required: true %>
                <div class="invalid-feedback">
                  <%= f.error :name %>
                </div>
              </div>
            </div>

            <div class="col-md-6">
              <div class="form-group mb-5 d-flex flex-column align-items-start">
                <p><%= f.label :first_name, 'Prénom' %></p>
                <%= f.text_field :first_name, class: 'form-control w-100', required: true %>
                <div class="invalid-feedback">
                  <%= f.error :first_name %>
                </div>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6">
              <div class="form-group mb-5 d-flex flex-column align-items-start">
                <p><%= f.label :email, 'Adresse e-mail' %></p>
                <%= f.email_field :email, class: 'form-control', required: true %>
                <div class="invalid-feedback">
                  <%= f.error :email, message: "Adresse e-mail invalide" %>
                </div>
              </div>
            </div>
            <div class="col-md-6">
            <div class="form-group mb-5 d-flex flex-column align-items-start">
              <p><%= f.label :phone, 'Téléphone' %></p>
              <%= f.text_field :phone, class: 'form-control', required: true %>
              <div class="invalid-feedback">
                <%= f.error :phone, message: "Format de téléphone invalide" %>
              </div>
            </div>
          </div>

          <div class="d-flex justify-content-center w-100">
            <div class="d-flex flex-column">
              <p><%= f.label :budget, 'Budget' %></p>
              <%= f.select :budget, ["inférieur à 10000 €", "Entre 10000 et 15000 €", "Entre 15000 et 50000 €", "supérieur à 50000 €"], {}, { class: 'form-select mb-5 w-100', required: true } %>
              <div class="invalid-feedback">
                <%= f.error :budget %>
              </div>
            </div>
          </div>


          <div class="form-group mb-5">
            <p><%= f.label :message, 'Votre projet' %></p>
            <%= f.text_area :message, class: 'form-control', rows: 5, required: true %>
            <div class="invalid-feedback">
              <%= f.error :message %>
            </div>
          </div>

            <div class="form-actions bg-dark text-center">
              <%= f.button :submit, "Confirm", class: "text-white" %>
            </div>
          </div>
        <% end %>

        <% if flash[:success] %>
          <div class="alert alert-success">
            <%= flash[:success] %>
          </div>
        <% elsif flash[:error] %>
          <div class="alert alert-danger">
            <%= flash[:error] %>
          </div>
        <% end %>

        <script>
          document.addEventListener("DOMContentLoaded", function() {
            var forms = document.querySelectorAll('.needs-validation');

            Array.from(forms).forEach(function(form) {
              form.addEventListener('submit', function(event) {
                if (!form.checkValidity()) {
                  event.preventDefault();
                  event.stopPropagation();
                }

                form.classList.add('was-validated');
              }, false);
            });
          });
        </script>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Helivo : Agence de développement web</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <%= favicon_link_tag %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="about-banner"></div>
<div class="container">
  <h3 style="font-size: 32px; font-weight: bold;">Qui sommes-nous ?</h3>
  <hr>
  <p><strong style="color: #565973;">Bienvenue chez Helivo, votre partenaire de confiance pour propulser votre présence en ligne à de nouveaux sommets.</strong> En tant que jeune agence de développement web, nous sommes déterminés à redéfinir les normes du secteur en combinant habilement l'intelligence artificielle et le développement web pour offrir des solutions rapides, efficaces et économiques.</p>
  <br>
  <br>
  <p style="text-decoration: underline;">Nos Valeurs :</p>
  <br>
  <p><strong style="color: #565973;">Chez Helivo, la satisfaction de nos clients est notre boussole.</strong> Nous nous engageons à respecter nos engagements et à mener tous les projets de A à Z, garantissant ainsi des résultats concrets et dépassant les attentes. Notre équipe expérimentée excelle dans l'art de la collaboration active, centrée sur la réussite de nos clients. En choisissant Helivo, vous optez pour une expertise inégalée et un engagement envers la croissance de votre visibilité en ligne.</p>
  <br>
  <p style="text-decoration: underline;">Ce Qui Nous Rend Uniques :</p>
  <br>
  <p><strong style="color: #565973;">Alliance de l'IA et du Développement Web :</strong> Helivo repousse les limites en fusionnant l'intelligence artificielle et le développement web, créant ainsi une synergie puissante pour des résultats rapides.</p>
  <br>
  <p><strong style="color: #565973;">Avantage Financier :</strong> Nos processus accélérés et nos coûts optimisés grâce à l'IA se traduisent par un avantage financier significatif pour nos clients.</p>
  <br>
  <p><strong style="color: #565973;">Expertise Inégalée :</strong> Notre équipe compétente déploie son savoir-faire pour délivrer des résultats au-delà des attentes, offrant ainsi une valeur ajoutée à chaque projet.</p>
  <br>
  <p><strong style="color: #565973;">Suivi Personnalisé :</strong> Chaque client bénéficie d'un suivi personnalisé avec un interlocuteur unique, garantissant une communication transparente et une compréhension approfondie des besoins.</p>
  <br>
  <p><strong style="color: #565973;">Rapport Qualité-Prix Imbattable :</strong> Helivo s'engage à fournir des solutions de qualité exceptionnelle à un prix compétitif, grâce à nos techniques de production optimisées par l'IA.</p>
  <br>
  <br>
  <p><strong style="color: #565973;">Ensemble, Accélérons Votre Succès en Ligne avec Helivo.</strong></p>
</div>

app/views/pages/blog.html.erb
<div class="container">
  <h3 style="color: #7071e8; font-weight: bold; font-size: 36px; margin-top: 50px;">Blog</h3>
  <div class="choix-sujet">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link link-dark active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane" aria-selected="true">Tous les sujets</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link link-dark" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false">SEO</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link link-dark" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact-tab-pane" type="button" role="tab" aria-controls="contact-tab-pane" aria-selected="false">Refonte</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link link-dark" id="disabled-tab" data-bs-toggle="tab" data-bs-target="#disabled-tab-pane" type="button" role="tab" aria-controls="disabled-tab-pane" aria-selected="false">Culture</button>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab" tabindex="0">
        <%= link_to article_path do %>
          <div class="card text-bg-dark w-50" style="width: 18rem; margin-top: 40px; border-radius: 5px;">
            <%= image_tag "banner_Article1.png", class: "img-card-blog" %>
            <div class="card-body">
              <h3 class="card-title" style="font-weight: 600; font-size: 24px">Maximiser la Présence en Ligne : Stratégies de Trafic Web Propulsées par l'IA</h3>
              <p class="card-text" style="color: #7071e8; font-weight: 300;">30 novembre 2023 | SEO</p><br>
              <p class="card-text">Dans l'ère du marketing digital en constante évolution, la présence en ligne est devenue cruciale pour la croissance des entreprises. À l'heure où le...</p>
            </div>
          </div>
        <% end %>
      </div>
      <div class="tab-pane fade" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">
        <div class="card text-bg-dark w-50" style="width: 18rem; margin-top: 40px; border-radius: 5px;">
          <%= image_tag "banner_Article1.png", class: "img-card-blog" %>
          <div class="card-body">
            <h3 class="card-title" style="font-weight: 600; font-size: 24px">Maximiser la Présence en Ligne : Stratégies de Trafic Web Propulsées par l'IA</h3>
            <p class="card-text" style="color: #7071e8; font-weight: 300;">30 novembre 2023 | SEO</p><br>
            <p class="card-text">Dans l'ère du marketing digital en constante évolution, la présence en ligne est devenue cruciale pour la croissance des entreprises. À l'heure où le...</p>
          </div>
        </div>
      </div>
      <div class="tab-pane fade" id="contact-tab-pane" role="tabpanel" aria-labelledby="contact-tab" tabindex="0">...</div>
      <div class="tab-pane fade" id="disabled-tab-pane" role="tabpanel" aria-labelledby="disabled-tab" tabindex="0">...</div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="landing-banner">
  <div class="headingcontent">
    <h1 class="titre">
      <span>Votre Succès, </span><br>
      <span class="couleur-accent">Notre Code</span>
    </h1>

    <div class="sous-titre">
      <span class="texte-accroche">
        Explorez de nouveaux horizons numériques avec Helivo, <span class="texte-accroche-gras">votre partenaire de confiance</span> en développement web. Projets sur mesure, modernisation efficace, maintenance proactive et contenu SEO stratégique. Optez pour Helivo, où l'intelligence artificielle redéfinit la norme.
      </span>
    </div>

    <div class="button-frame">
      <button class="boutoncontact">
        <b class="contactez-nous">Contactez nous</b>
      </button>
    </div>

    <div class="details">
      <div class="detail">
        <%= image_tag "check.svg", alt: "Check Icon" %>
        <div class="avantage">Expertise</div>
      </div>
      <div class="detail">
        <%= image_tag "check.svg", alt: "Check Icon" %>
        <div class="avantage">Efficacité</div>
      </div>
      <div class="detail">
        <%= image_tag "check.svg", alt: "Check Icon" %>
        <div class="avantage">Rentabilité</div>
      </div>
    </div>
  </div>
</div>

      <div class="conteneur-services" id="services">
        <h2 class="titre-services">Nos Services</h2>
        <div class="service">
            <%= image_tag "icon_services_1.png", style: "width:150px; height: 150px;" %>
          <div class="titre-et-texte-service">
            <h3 class="titre-service">Projets sur mesure</h3>
            <div class="texte-service">
              <p>Optimisez la productivité de votre entreprise avec nos Projets sur mesure, offrant des solutions personnalisées pour une croissance rapide et efficace.</p>
            </div>
          </div>
        </div>
        <div class="service">
          <%= image_tag "icon_service_2.png", style: "width:150px; height: 150px;" %>
          <div class="titre-et-texte-service">
            <h3 class="titre-service">Modernisation de projets</h3>
            <div class="texte-service">
              <p>Transformez rapidement votre projet pour une présence digitale performante, dépassant la concurrence et atteignant vos objectifs de manière rentable.</p>
            </div>
          </div>
        </div>
        <div class="service">
          <%= image_tag "icon_service_3.png", style: "width:150px; height: 150px;" %>
          <div class="titre-et-texte-service">
            <h3 class="titre-service">Maintenance active</h3>
            <div class="texte-service">
              <p>Assurez une disponibilité maximale et une expérience utilisateur optimale en anticipant les problèmes grâce à notre service de Maintenance active pour votre site.</p>
            </div>
          </div>
        </div>
        <div class="service">
          <%= image_tag "icon_services_4.png", style: "width:150px; height: 150px;" %>
          <div class="titre-et-texte-service">
            <h3 class="titre-service">Contenu SEO stratégique</h3>
            <div class="texte-service">
              <p>Maximisez la visibilité en ligne avec notre stratégie de contenu SEO alimentée par l'IA, générant rapidement des résultats exceptionnels tout en optimisant votre budget.</p>
            </div>
          </div>
        </div>
      </div>

<div class="notre-mission">
  <div class="notre-mission-frame">
    <div class="texte-notre-mission">
      <h2 class="titre-notre-mission">Notre Mission</h2>
      <p class="texte-notre-mission">Exceller dans le numérique avec Efficacité et Fiabilité.</p>
    </div>
    <div class="row mb-5">
      <div class="col-md-5">
        <%= image_tag "notremission_img1.png", class: "img-nm" %>
      </div>
      <div class="col-md-2"></div>
      <div class="col-md-5">
        <p>Chez Helivo, notre <strong>engagement</strong> premier est votre <strong>satisfaction</strong>. Nous nous distinguons par notre respect des engagements, prenant en charge chaque projet de sa conception à sa réalisation intégrale. Forts d'une expertise pointue, nous garantissons des résultats dépassant vos attentes. Avec un interlocuteur dédié pour un suivi personnalisé, nous vous offrons une expérience unique, alliant <strong>qualité</strong> exceptionnelle et tarifs compétitifs grâce à nos techniques de production alimentées par l'IA.</p>
      </div>
    </div>
    <div class="row mt-5">
      <div class="col-md-5">
        <p>À travers notre approche axée sur l'excellence, nous nous efforçons constamment d'<strong>innover</strong> et d'<strong>optimiser</strong> nos méthodes de travail pour répondre aux besoins spécifiques de chaque client. Notre équipe dévouée, composée d'experts chevronnés, s'engage à maintenir un niveau élevé de qualité et de fiabilité à toutes les étapes du processus. En investissant dans des technologies de pointe et en restant à l'affût des dernières avancées, nous sommes en mesure de garantir des solutions <strong>avant-gardistes</strong> et parfaitement adaptées à votre projet.</p>
      </div>
      <div class="col-md-2"></div>
      <div class="col-md-5">
        <%= image_tag "Notremission_img2.jpg", class: "img-nm" %>
      </div>
    </div>
  </div>
</div>

<div class="info">
  <div class="item">
        <h2 class="info-titre-principal">Au cœur de notre savoir-faire, la création rapide de solutions web intelligentes.</h2>
        <p class="text-info-helivo"><strong>Chez Helivo</strong>, notre passion et notre expertise se concentrent sur la fusion harmonieuse entre l'<strong>intelligence artificielle (IA)</strong> et le <strong>développement web</strong>. Nous sommes spécialisés dans la création de solutions web sur mesure, révolutionnant la façon dont les entreprises abordent le développement de nouveaux produits en ligne.</p>
    </div>

    <div class="item">
        <p class="text-info-helivo">Nous <strong>excellons dans la conception et le développement d'applications web</strong> à la pointe de la technologie, intégrant des fonctionnalités intelligentes grâce à notre expertise en <strong>IA</strong>. Notre approche est centrée sur la résolution de problématiques business et techniques complexes pour offrir des solutions performantes.</p>
        <%= image_tag "NE_img1.png" %>
    </div>

    <div class="item">
        <%= image_tag "NE_img2.png" %>
        <p class="text-info-helivo">Votre succès est notre priorité, et notre équipe expérimentée propose des conseils stratégiques basés sur une <strong>vision 360 des enjeux produits</strong>. De la sélection de la stack technique à la définition de partenariats stratégiques, en passant par l'optimisation de l'<strong>expérience utilisateur (UX/UI)</strong> et les aspects liés à l'acquisition et au financement, nous vous accompagnons à chaque étape.</p>
    </div>

    <div class="item">
        <p class="text-info-helivo">Notre alliance unique de <strong>l'IA et du développement web</strong> nous permet de vous offrir des délais de livraison exceptionnellement rapides. Les processus accélérés et les coûts optimisés résultent en un <strong>avantage financier indéniable pour votre entreprise</strong>, sans compromis sur la qualité.</p>
        <%= image_tag "NE_img3.png" %>
    </div>

    <div class="item">
        <%= image_tag "NE_img4.png" %>
        <p class="text-info-helivo">Au-delà du développement, nous sommes des experts en <strong>création de contenu avec l'IA</strong>, garantissant une <strong>visibilité en ligne optimale</strong>. Notre engagement envers la <strong>croissance de votre visibilité</strong> se traduit par des stratégies <strong>SEO stratégiques</strong> et un <strong>contenu qui se démarque</strong> dans un monde numérique en constante évolution.</p>
    </div>
</div>

      <div class="contactus" id="contact">
        <div class="contactusframe">
          <h2 class="titre-contact">Prêt à commencer ?</h2>
          <div class="text-contact">
            <p>Contactez nous par email pour discuter de votre besoin</p>
          </div>
          <div class="button-frame">
            <button class="boutoncontact">
              <b class="contactez-nous">Contactez nous</b>
            </button>
          </div>
        </div>
      </div>
      <div class="space"></div>
      <div id="footer"></div>

app/views/services/contenu_seo_strategique.html.erb
<div class="container" style="margin-bottom: 100px;">
  <div class="row" style="margin-top: 100px;">
    <h2 style="color: #7071E8; font-weight: bold; margin-bottom: 20px;">Contenu SEO Stratégique</h2>
    <div class="col-md-12"><p style="font-size: 18px">Bienvenue chez Helivo, votre partenaire de confiance pour une présence en ligne optimale. Découvrez notre service exclusif de <span style="color: #7071E8;">Contenu SEO Stratégique</span>, propulsé par notre expertise de pointe en création de contenu assistée par l'IA. Avec Helivo, transformez votre visibilité en ligne et démarquez-vous de la concurrence grâce à une stratégie SEO qui fait toute la différence.</p></div>
  </div>
</div>
<%= image_tag 'psm_banner.png', class: "psm_banner" %>
<div class="container" style="width: 80%; margin-top: 50px;">
  <h3 class="title-psm">Pourquoi choisir notre <span style="color: #7071E8;">Contenu SEO Stratégique ?</span></h3>
  <p class="mb-4">Chez Helivo, nous comprenons l'importance cruciale d'une présence en ligne bien optimisée. C'est pourquoi nous avons mis en place des algorithmes intelligents et des processus accélérés pour créer un contenu SEO rapidement et de manière rentable. Notre avantage distinct réside dans l'alliance synergique entre l'IA et le développement web, vous garantissant une stratégie de contenu SEO qui maximise l'efficacité de votre budget.</p>
  <p class="text-psm" style="font-weight: bold;">Les avantages de notre service :

</p>
  <div id="carouselExampleCaptions" class="carousel slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag 'carroussel1.png', class: "psm-img-carroussel" %>
      <div class="carousel-caption d-none d-md-block">
        <h3 style="font-weight: bold; font-size: 20px; margin-bottom: 10px;">Optimisation Rapide :</h3>
        <p>Grâce à notre expertise en intelligence artificielle, nous produisons un contenu SEO optimisé en un temps record, vous permettant de voir des résultats exceptionnels plus rapidement.</p>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'carroussel2.png', class: "psm-img-carroussel" %>
      <div class="carousel-caption d-none d-md-block">
        <h3 style="font-weight: bold; font-size: 20px; margin-bottom: 10px;">Coût Optimisé :</h3>
        <p>Notre approche innovante combine l'efficacité de l'IA avec des processus de développement web optimisés, ce qui se traduit par des coûts compétitifs et une valeur exceptionnelle pour nos clients.</p>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'carroussel3.png', class: "psm-img-carroussel" %>
      <div class="carousel-caption d-none d-md-block">
        <h3 style="font-weight: bold; font-size: 20px; margin-bottom: 10px;">Stratégie Personnalisée :</h3>
        <p>Chaque projet est unique, c'est pourquoi notre équipe dédiée collabore étroitement avec vous pour comprendre vos besoins spécifiques et élaborer une stratégie de contenu SEO sur mesure.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
  <div style="margin-top: 75px;">
    <h2 class="mb-3" style="font-weight: bold;">IA et SEO : Votre Succès en Trois Étapes</h2>
    <p class="mb-3">Chez Helivo, notre <strong>Contenu SEO Stratégique</strong> tire sa puissance de l'intelligence artificielle, offrant une optimisation SEO rapide et agile.</p>
    <ul>
      <li><strong>Analyse Ciblée :</strong> L'IA accélère l'identification des besoins, combinant audits techniques et entretiens pour une analyse précise.</li><br>
      <li><strong>Validation Dynamique :</strong> Collaborant avec vos équipes, l'IA dérisque le projet en validant dynamiquement le périmètre, garantissant une valeur maximale.</li><br>
      <li><strong>Développement Agile :</strong> Grâce à l'IA, notre approche itérative est rapide et précise, assurant une adaptation constante et la satisfaction des utilisateurs.</li><br>
    </ul>
    <h2 class="mb-3" style="font-weight: bold;">Pourquoi l'IA ?</h2>
    <ul>
      <li><strong>Rapidité et Agilité</strong></li>
      <li><strong>Validation Précise du Périmètre</strong></li>
      <li><strong>Anticipation des Besoins SEO</strong></li>
    </ul>
    <p>L'IA propulse votre présence en ligne vers le succès. Prêts à maximiser votre visibilité ? Discutons de votre projet dès maintenant.</p>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-content">
      <div class="footer-logo">
          <%= image_tag "logo_Upscale2x1.png" %>
          <p>Helivo</p>
      </div>
      <div class="footer-links">
          <a href="#">Termes et conditions</a>
          <a href="#">Politique de confidentialité</a>
      </div>
  </div>
  <div class="footer-bottom">
      <p class="copyright">© Helivo tous droits réservés 2023</p>
      <p class="made-by">Made with <span class="heart-symbol">&hearts;</span> by Quentin Langlois</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo_Upscale2x1.png" %>
      <span class="brand-text">Helivo</span>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav me-auto">
    <%# if user_signed_in? %>
      <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <button class="btn text-light dropdown-toggle" style="font-family: 'Montserrat', sans-serif;" data-bs-toggle="dropdown" aria-expanded="false">
            SERVICES
          </button>
          <ul class="dropdown-menu dropdown-menu-dark">
            <li><%= link_to "Projets sur mesure", services_projets_sur_mesure_path, class: "lien-service dropdown-item" %></li>
            <li><%= link_to "Modernisation de projets", services_modernisation_projets_path, class: "lien-service dropdown-item" %></li>
            <li><%= link_to "Maintenance active", services_maintenance_active_path, class: "lien-service dropdown-item" %></li>
            <li><%= link_to "Contenu SEO stratégique", services_contenu_seo_strategique_path, class: "lien-service dropdown-item" %></li>
          </ul>
        </li>
      </ul>
    </div>
      <li class="nav-item">
        <%= link_to "BLOG", blog_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "A PROPOS", about_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "NOUS CONTACTER", new_contact_path, class: "nav-link" %>
      </li>
    <%# else %>
      <!--li class="nav-item"-->
        <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
      <!--/li-->
    <%# end %>
  </ul>
</div>

  </div>
</div>